jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com
 
      - name: Install dep
        run: |
          yarn install --dev
      - name: Generate Artifact
        run: |
         rm -rf dist && mkdir dist
         zip -r dist.zip . -r ./dist/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./dist
      - env: 
         GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
        name: make a release
        run: npx semantic-release
      - name: Clean
        run: |
          make clean
    
name: Manual Test
"on":
  workflow_dispatch: {}