jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Package
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: dist.zip
          repo: elaheabs/my-github-actions
          target: release.zip
    
name: Artifact-cd
"on":
  workflow_dispatch: {}

