on:
  release:
    types:
      - released
name: semantic-release
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: make a deploymeny
        run: echo deployment
     

