on:
  push:
    branches:
      - main
name: Build
jobs:
  dep1:
    runs-on: ubuntu-latest
    steps:
      - name: Run FAILING script
        run: exit 1 
  job:
    runs-on: ubuntu-latest
    if: ${{ needs.dep1.result == 'success' }}
    needs: [dep1]
    steps:
      - name: Hello World         
        run: |
          echo "this job is run hehe"
  nextjob:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"