on:
  push:
    branches:
      - main
name: release-please
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npx semantic-release
      - env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
