on:
  push:
    branches:
      - main
name: Build
jobs:
  dep1:
    runs-on: ubuntu-latest
    steps:
      - name: Run FAILING script
        run: exit 1 
  dep2:
    runs-on: ubuntu-latest
    steps:
      - name: Run succeed script
        run: echo "dep2 succeed"
  job:
    runs-on: ubuntu-latest
    if: ${{ needs.dep2.result == 'success' }}
    needs: [dep2]
    steps:
      - name: Hello World         
        run: |
          echo "this job is run hehe"
  nextjob:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"