on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: npx semantic-release
      - env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
