# This is a basic workflow to help you get started with Actions

name: my first workflow
on: 
 push: 
   branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build the project (Run a one-line script)
        run: npm run build

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
